### PR TITLE
feature: cpd-741 add total emails sent and clicked to overview

### PR DESCRIPTION
**Pull request by itsmostafa**
add aggregate level stats: total emails sent and total emails clicked 

## 🧪 Testing ##
tested locally

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by dylanj1752 — APPROVED** [review]
LGTM

**Comment by itsmostafa** [comment]
hey @dav3r the gh actions on this PR are failing at the black hook id with this error:
`ImportError: cannot import name '_unicodefun' from 'click'`

I did a quick search and it seems a recent version of the click package is breaking which i'm assuming is a dependency of this hook:
https://github.com/dask/distributed/issues/6013

how would you like me to move forward? Should I comment this hook out for now? Thanks

**Comment by dav3r** [comment]
> hey @dav3r the gh actions on this PR are failing at the black hook id with this error: `ImportError: cannot import name '_unicodefun' from 'click'`
> 
> I did a quick search and it seems a recent version of the click package is breaking which i'm assuming is a dependency of this hook: [dask/distributed#6013](https://github.com/dask/distributed/issues/6013)
> 
> how would you like me to move forward? Should I comment this hook out for now? Thanks

You should be able to update your pre-commit hooks to get past this issue until we are able to push out a skeleton update that will address this.  Please see https://github.com/cisagov/skeleton-generic/pull/105 for more info.  If you have any questions, @mcdonnnj will be happy to answer them. 😄

**Comment by itsmostafa** [comment]
> 

Sounds good. I'll reach out to @mcdonnnj next time :)

**Comment by itsmostafa** [comment]
> > hey @dav3r the gh actions on this PR are failing at the black hook id with this error: `ImportError: cannot import name '_unicodefun' from 'click'`
> > I did a quick search and it seems a recent version of the click package is breaking which i'm assuming is a dependency of this hook: [dask/distributed#6013](https://github.com/dask/distributed/issues/6013)
> > how would you like me to move forward? Should I comment this hook out for now? Thanks
> 
> You should be able to update your pre-commit hooks to get past this issue until we are able to push out a skeleton update that will address this. Please see [cisagov/skeleton-generic#105](https://github.com/cisagov/skeleton-generic/pull/105) for more info. If you have any questions, @mcdonnnj will be happy to answer them. 😄

Sounds good I'll reach out to @mcdonnnj next time :)

**Pull request merged**
