### PR TITLE
feature: cpd-713 disable lpd field in sending profile and hyperlink from template testing

### PR DESCRIPTION
**Pull request by itsmostafa**
## 🗣 Description ##
- Disable landing page domain field in sending profile to encourage using the landing page domain field in the subscription details view instead
- route to template details view when clicking on a template in email sent list in the subscription testing tab
- Add Appendix A Date field to Customer Edit Page

## 🧪 Testing ##
Tested locally

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by dylanj1752 — APPROVED** [review]
LGTM

**Comment by itsmostafa** [comment]
@dav3r can you please approve this? I'm assuming i'm blocked from merging due to modifying the `CODEOWNERS` file. thanks!

**Comment by dav3r** [comment]
> @dav3r can you please approve this? I'm assuming i'm blocked from merging due to modifying the `CODEOWNERS` file. thanks!

I can, but first I'll ask if you have any reason to comment out this block, rather than simply delete it:
https://github.com/cisagov/con-pca-web/blob/5a86bd3cc7aba627f63ae63e9a6f75c410c191d8/src/AdminUI/src/app/components/subscriptions/manage-subscription/subscription-testing-tab/subscription-testing-tab.component.ts#L117-L130

Generally, we try to avoid checking in commented-out blocks of code like this.

**Comment by itsmostafa** [comment]
> > @dav3r can you please approve this? I'm assuming i'm blocked from merging due to modifying the `CODEOWNERS` file. thanks!
> 
> I can, but first I'll ask if you have any reason to comment out this block, rather than simply delete it:
> 
> https://github.com/cisagov/con-pca-web/blob/5a86bd3cc7aba627f63ae63e9a6f75c410c191d8/src/AdminUI/src/app/components/subscriptions/manage-subscription/subscription-testing-tab/subscription-testing-tab.component.ts#L117-L130
> 
> Generally, we try to avoid checking in commented-out blocks of code like this.



> 

I may have to reference this block of code in the near future in case more work needs to be done relating to this feature. Figured it'd be simpler to keep it in there and uncomment and rework if it is needed. But if you'd like me to remove it, that's fine too. I can paste this code block in jira or elsewhere

**Comment by dav3r** [comment]
> I may have to reference this block of code in the near future in case more work needs to be done relating to this feature. Figured it'd be simpler to keep it in there and uncomment and rework if it is needed. But if you'd like me to remove it, that's fine too. I can paste this code block in jira or elsewhere

Our philosophy has been that if you need the code, you can always find it in the git history.  That's also a good reason to do a single commit to remove that block, so that you can easily revert that commit later if you think you might need that code back.

**Review by dav3r — APPROVED** [review]
Approved for the justified change to the `CODEOWNERS` file. 👍

**Comment by itsmostafa** [comment]
> 

@dav3r thanks! Please expect more of these codeowner changes in other repositories. Will get to them soon

**Pull request merged**
